Resources:
  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: mindburn-websocket-api
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action
      
  WebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref WebSocketApi
      StageName: prod
      AutoDeploy: true
      DefaultRouteSettings:
        DetailedMetricsEnabled: true
        ThrottlingBurstLimit: 500
        ThrottlingRateLimit: 300
      
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $connect
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref WebSocketAuthorizer
      OperationName: ConnectHandler
      Target: !Sub integrations/${ConnectIntegration}
      
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $disconnect
      OperationName: DisconnectHandler
      Target: !Sub integrations/${DisconnectIntegration}
      
  SubscribeRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: subscribe
      OperationName: SubscribeHandler
      Target: !Sub integrations/${SubscribeIntegration}
      
  UnsubscribeRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: unsubscribe
      OperationName: UnsubscribeHandler
      Target: !Sub integrations/${UnsubscribeIntegration}
      
  WebSocketAuthorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties:
      ApiId: !Ref WebSocketApi
      AuthorizerType: REQUEST
      AuthorizerUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketAuthorizerFunction.Arn}/invocations
      IdentitySource:
        - route.request.querystring.token
      Name: WebSocketAuthorizer
      
  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: mindburn-websocket-connections
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
        - AttributeName: subscriptionType
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: SubscriptionTypeIndex
          KeySchema:
            - AttributeName: subscriptionType
              KeyType: HASH
          Projection:
            ProjectionType: ALL
            
  WebSocketAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/websocket/authorizer
      Handler: index.handler
      Runtime: nodejs20.x
      MemorySize: 256
      Timeout: 5
      Environment:
        Variables:
          AUTH_TABLE: !Ref AuthTable
          
  ConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/websocket/connect
      Handler: index.handler
      Runtime: nodejs20.x
      MemorySize: 256
      Timeout: 5
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref ConnectionsTable
          
  DisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/websocket/disconnect
      Handler: index.handler
      Runtime: nodejs20.x
      MemorySize: 256
      Timeout: 5
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref ConnectionsTable
          
  SubscribeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/websocket/subscribe
      Handler: index.handler
      Runtime: nodejs20.x
      MemorySize: 256
      Timeout: 5
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref ConnectionsTable
          
  UnsubscribeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/websocket/unsubscribe
      Handler: index.handler
      Runtime: nodejs20.x
      MemorySize: 256
      Timeout: 5
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref ConnectionsTable
          
  BroadcastFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/websocket/broadcast
      Handler: index.handler
      Runtime: nodejs20.x
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref ConnectionsTable
          WEBSOCKET_ENDPOINT: !Sub ${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${WebSocketStage}
          
Outputs:
  WebSocketApiEndpoint:
    Description: WebSocket API Endpoint
    Value: !Sub wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${WebSocketStage} 