name: Verification Engine CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'packages/verification-engine/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'packages/verification-engine/**'

env:
  AWS_REGION: us-east-1
  NODE_VERSION: 18

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd packages/verification-engine
          npm ci

      - name: Run linter
        run: |
          cd packages/verification-engine
          npm run lint

      - name: Run tests
        run: |
          cd packages/verification-engine
          npm run test:ci

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          directory: ./packages/verification-engine/coverage
          flags: verification-engine

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Run dependency scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    needs: [test, security]
    if: github.ref == 'refs/heads/develop'
    environment: dev

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: |
          cd packages/verification-engine
          npm ci

      - name: Deploy to dev
        run: |
          cd packages/verification-engine
          npm run deploy:dev

      - name: Run smoke tests
        run: |
          cd packages/verification-engine
          npm run test:smoke

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [test, security]
    if: github.ref == 'refs/heads/main'
    environment: prod

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: |
          cd packages/verification-engine
          npm ci

      - name: Deploy to prod
        run: |
          cd packages/verification-engine
          npm run deploy:prod

      - name: Run smoke tests
        run: |
          cd packages/verification-engine
          npm run test:smoke

      - name: Notify deployment
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'deployments'
          slack-message: 'Verification Engine deployed to production :rocket:'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }} 